### ISSUE TITLE
@alteryx/ui@1.3.0 throws deprecation errors

### ISSUE THREAD

**Issue by AlionaSidarenkaTR** [alteryx/alteryx-ui#16]
@alteryx/ui@1.3.0 component ListBox/ListBoxActionBar uses justify property for Grid, but it is deprecated (justifyContent should be used instead). This leads to this console.error
![image](https://user-images.githubusercontent.com/18561722/126770224-47109929-efde-4dac-bba3-aa2037cce304.png)
 
 Also @alteryx/ui/styles/colorManipulator uses fade function, this also leads to deprecation error:
![image](https://user-images.githubusercontent.com/18561722/126771848-0319952d-acbb-4f92-b7a5-a329b2b90950.png)

My package.json:
![image](https://user-images.githubusercontent.com/18561722/126771969-3e059b04-5b40-4656-8f45-26a9862c1a1a.png)

**Comment by jordan-quinn-alteryx** [comment]
Hey Aliona!

These deprecation warnings are known issues and won't be fixed until the next major for Alteryx UI. That's coming sometime soon. (: 

Thanks for logging this issue and we'll let you know as soon as the major is released.

**Comment by AlionaSidarenkaTR** [comment]
Thanks, @jordan-quinn-alteryx
