### ISSUE TITLE
Using SDK workspaces with Git: sub-repositories in workspace

### ISSUE THREAD

**Issue by neurotroph** [alteryx/alteryx-ui#7]
Hi Alteryx team,

I would like to manage by Alteryx custom plugins with Git, so I usually have a Git repository for a whole tool family. When using the new SDK and creating an SDK workspace, the CLI seems to clone the [dev-harness repository](https://github.com/alteryx/dev-harness) for each tool. While this presents a nice flow for the developer and always uses the latest version, it also means that I have repositories in my repository. As the clone repo for each tool is still linked to the repository on GitHub, it means that committing changes and pushing to our company Git server is getting tricky.

Is there a solution apart from deleting `.git` folders manually? It might be better to clone/download the repo and remove all references to the original repository.

Best
Christopher

PS: As the `alteryx_plugin_cli` does not have its own repository on GitHub, I'm not sure where to post the issue. :)

**Comment by williammalone** [comment]
Hi Christopher,

Thanks for the feedback! I have passed it along to the CLI team. I'll let you know when I hear more.

**Comment by jordan-quinn-alteryx** [comment]
@neurotroph The CLI team created a story to address this issue. No ETA on the fix yet, but we'll keep you posted once it's merged in and released! Thanks for your patience.
